pocket/financial/urls.py
from django.urls import path

from pocket.financial import views as v

app_name = 'financial'

urlpatterns = [
    path('', v.ExpenseListView.as_view(), name='expense_list'),
    path('not-paid/', v.ExpenseNotPaidListView.as_view(), name='expense_not_paid_list'),  # noqa E501
    path('<int:pk>/', v.ExpenseDetailView.as_view(), name='expense_detail'),
    path('create/', v.ExpenseCreateView.as_view(), name='expense_create'),
    path('<int:pk>/update/', v.ExpenseUpdateView.as_view(), name='expense_update'),
    path('<int:pk>/delete/', v.ExpenseDeleteView.as_view(), name='expense_delete'),
]

pocket/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pocket.core.urls', namespace='core')),
    path('accounts/', include('pocket.accounts.urls')),  # without namespace
    path('crm/', include('pocket.crm.urls', namespace='crm')),
    path('financial/', include('pocket.financial.urls', namespace='financial')),
    path('admin/', admin.site.urls),
]

pocket/financial/models.py
from django.db import models
from django.urls import reverse_lazy

from pocket.core.models import TimeStampedModel
from pocket.crm.models import Person


class Expense(TimeStampedModel):
    description = models.CharField('descrição', max_length=100)
    payment_date = models.DateField('data de pagamento', null=True, blank=True)
    person = models.ForeignKey(
        Person,
        on_delete=models.SET_NULL,
        verbose_name='pago a',
        related_name='expenses',
        null=True,
        blank=True
    )
    value = models.DecimalField('valor', max_digits=7, decimal_places=2)
    paid = models.BooleanField('pago', default=False)
    payment_voucher = models.ImageField(
        'comprovante',
        upload_to='',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('-payment_date',)
        verbose_name = 'despesa'
        verbose_name_plural = 'despesas'

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse_lazy('financial:expense_detail', kwargs={'pk': self.pk})

pocket/financial/forms.py
from django import forms

from .models import Expense


class ExpenseForm(forms.ModelForm):
    required_css_class = 'required'

    payment_date = forms.DateField(
        label='Data de pagamento',
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
            }),
        input_formats=('%Y-%m-%d',),
        required=False,
    )

    class Meta:
        model = Expense
        fields = ('description', 'payment_date', 'person', 'value', 'payment_voucher')  # noqa E501

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        print('User:', self.request.user)
        super(ExpenseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        if self.fields.get('paid'):
            self.fields['paid'].widget.attrs['class'] = None
        if self.fields.get('payment_voucher'):
            self.fields['payment_voucher'].widget.attrs['class'] = None


class ExpenseEditForm(ExpenseForm):

    class Meta:
        model = Expense
        fields = ExpenseForm.Meta.fields + ('paid',)

pocket/financial/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin as LRM
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from pocket.crm.models import Person

from .forms import ExpenseEditForm, ExpenseForm
from .mixins import (
    ExpenseContextDataMixin,
    ExpenseFormKwargsMixin,
    SearchMixin,
)
from .models import Expense


class ExpenseListView(LRM, ExpenseContextDataMixin, SearchMixin, ListView):
    model = Expense
    # context_object_name = 'expense_list'
    paginate_by = 5
    # template_name = 'expense_list.html'

    # @method_decorator(login_required)
    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.is_authenticated:
    #         message = 'Você não tem permissão para acessar essa página.'
    #         messages.error(request, message)
    #         return redirect('core:index')
    #     return super(ExpenseListView, self).dispatch(request, *args, **kwargs)


class ExpenseNotPaidListView(ExpenseContextDataMixin, SearchMixin, ListView):
    model = Expense
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(paid=False)


class ExpenseDetailView(DetailView):
    model = Expense


class ExpenseCreateView(ExpenseFormKwargsMixin, CreateView):
    model = Expense
    form_class = ExpenseForm
    success_url = reverse_lazy('financial:expense_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # user = self.request.user
        person = Person.objects.get(first_name='Huguinho')
        context['huguinho_expenses'] = Expense.objects.filter(person=person)
        return context

    def post(self, request, *args, **kwargs):
        print('>>> POST')
        # Serve pra debugar o código e pegar os valores do formulário.
        # request.POST
        # request.FILES
        # form = self.get_form()
        # form.is_valid()
        # form.errors
        # Exemplificar isso aqui.
        form = super().post(request, *args, **kwargs)
        return form

    def form_valid(self, form):
        # form.send_email()
        print('Enviar email')
        return super(ExpenseCreateView, self).form_valid(form)

    # def get_success_url(self):
    #     return reverse_lazy('financial:expense_list')

    def get_form_class(self):
        if self.request.user.is_authenticated:
            return ExpenseEditForm
        return ExpenseForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        print('>>>', kwargs)
        print()
        print('data:', kwargs.get('data'))
        print()
        print('files:', kwargs.get('files'))
        return kwargs


class ExpenseUpdateView(ExpenseFormKwargsMixin, UpdateView):
    model = Expense
    form_class = ExpenseEditForm


class ExpenseDeleteView(DeleteView):
    model = Expense
    success_url = reverse_lazy('expense:expense_list')

pocket/financial/templates/financial/expense_confirm_delete.html
<!-- expense_delete.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Deletar Despesa</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <p>Valor: {{ object.value }}</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'financial:expense_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

pocket/financial/templates/financial/expense_detail.html
<!-- expense_detail.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes de Despesa</h1>

  <ul>
    <li><b>Descrição:</b> {{ object.description }}</li>
    <li><b>Cliente:</b> {{ object.person|default:'---' }}</li>
    <li><b>Valor:</b> {{ object.value }}</li>
    <li><b>Data de pagamento:</b> {{ object.payment_date|date:'d/m/Y'|default:'---' }}</li>
  </ul>
{% endblock content %}

pocket/financial/templates/financial/expense_form.html
<!-- expense_form.html -->
{% extends "base.html" %}

{% block content %}
<h1>Despesa</h1>
<div class="row">
  <div class="col-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </form>
  </div>
  <div class="col-6">
    <h2>Despesas do Huguinho</h2>
    <ul>
      {% for expense in huguinho_expenses %}
      <li>{{ expense }}</li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock content %}

pocket/financial/templates/financial/expense_list.html
<!-- expense_list.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Lista de {{ verbose_name_plural }}</h1>

  <span class="pull-right">{{ object_list.count }}
    {% if object_list.count == 1 %}
      {{ verbose_name }}
    {% else %}
      {{ verbose_name_plural }}
  {% endif %}</span>

  <div class="row">
          <div class="col-md-auto">
            <a class="btn btn-primary" href="{% url 'financial:expense_create' %}">
              <i class="fa fa-plus"></i>
              Adicionar
            </a>
          </div>
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Busca..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Limpar</button>
                </div>
              </div>
            </form>
          </div>
        </div>

  <table class="table">
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Pago a</th>
        <th>Valor</th>
        <th>Data de pagamento</th>
        <th>Pago</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{{ object.get_absolute_url }}">{{ object.description }}</a>
          </td>
          <td>{{ object.person|default:'---' }}</td>
          <td>{{ object.value }}</td>
          <td>{{ object.payment_date|date:'d/m/Y'|default:'---' }}</td>
          <td>
            {% if object.paid %}
              <i class="fa fa-check ok"></i>
            {% else %}
              <i class="fa fa-times-circle no"></i>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'financial:expense_update' object.pk %}">
              <i class="fa fa-edit"></i>
            </a>
            <a href="{% url 'financial:expense_delete' object.pk %}" style="padding-left: 7px">
              <i class="fa fa-close no"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td></td>
        <td></td>
        <td>{{ total }}</td>
      </tr>
    </tfoot>
  </table>
  {% include "includes/pagination.html" %}
{% endblock content %}